name: CI Pipeline

on:
  push:
    branches: [main] #on push to main branch only the action will start

jobs:
  build:
    runs-on: ubuntu-latest #it will run on the latest fast ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Node Js
        uses: actions/setup-node@v3
        with:
            node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

